name: flet build windows

on: workflow_dispatch

env:
  PYTHONUTF8: 1

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Extract version numbers from pyproject.toml
        shell: pwsh
        run: |
          $regex_search = Select-String -Path pyproject.toml -Pattern 'requires-python\s*=\s*"~=\s*(\d+\.\d+)"'
          $PYTHON_VERSION = $regex_search.Matches.Groups[1].Value
          echo "PYTHON_VERSION=$PYTHON_VERSION"
          echo "PYTHON_VERSION=$PYTHON_VERSION" >> $env:GITHUB_ENV

          $regex_search = Select-String -Path pyproject.toml -Pattern 'version\s*=\s*"(.*)"'
          $PROJECT_VERSION = $regex_search.Matches.Groups[1].Value
          echo "PROJECT_VERSION=$PROJECT_VERSION"
          echo "PROJECT_VERSION=$PROJECT_VERSION" >> $env:GITHUB_ENV

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install Dumpbin
        uses: lorenalexm/install-dumpbin-action@main

      - name: Build Windows App
        shell: pwsh
        run: |
          pip install .
          python .\empaquetar.py
          cat D:\a\AsignacionAulica\AsignacionAulica\src\asignacion_aulica\pysidedeploy.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: asignacion-aulica-${{ env.PROJECT_VERSION }}-windows
          path: .\AsignaciónÁulica
          if-no-files-found: warn
          overwrite: false
